#!/usr/bin/env node
// gen-ai-docs.mjs — single-source the shared "Hard Rules" ruleset into the AI instruction files.
//
// The Hard Rules that get a PR rejected were hand-copied into CLAUDE.md, AGENTS.md and
// .github/copilot-instructions.md, so they drift the moment one is edited. This keeps them
// identical: the ruleset lives once in ai/partials/*.md and is injected into each instruction file
// inside a marker block. Everything OUTSIDE the markers stays hand-maintained.
//
// Usage:
//   node tools/gen-ai-docs.mjs          regenerate the instruction files in place (idempotent)
//   node tools/gen-ai-docs.mjs --check  exit 1 if any generated block is missing or stale
//
// CONTRIBUTING.md remains the human source of truth for the rules; edit the partial to match it,
// then run this. Config: ai/ai-docs.config.json.

import { createHash } from "node:crypto"
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join, relative } from "node:path"
import { fileURLToPath } from "node:url"

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..")
const CONFIG_REL = "ai/ai-docs.config.json"

const partialKey = stem => stem.replace(/^\d+-/, "")
const normalize = s => s.replace(/\r\n/g, "\n")

function loadPartials(absDir) {
  const out = {}
  if (!existsSync(absDir)) return out
  for (const name of readdirSync(absDir).sort()) {
    if (!name.endsWith(".md")) continue
    const abs = join(absDir, name)
    const content = normalize(readFileSync(abs, "utf8")).replace(/^\n+|\n+$/g, "")
    out[partialKey(name.replace(/\.md$/, ""))] = {
      srcRel: relative(REPO_ROOT, abs).replace(/\\/g, "/"),
      content
    }
  }
  return out
}

function blockFor(key, content, srcRel) {
  const sha = createHash("sha256").update(content, "utf8").digest("hex").slice(0, 8)
  const start = `<!-- AI-DOCS:${key} START v=${sha} — generated by tools/gen-ai-docs.mjs from ${srcRel}; edit the partial, not here -->`
  const end = `<!-- AI-DOCS:${key} END -->`
  return `${start}\n${content}\n${end}`
}

function upsertBlock(text, key, block) {
  const esc = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
  const re = new RegExp(`<!-- AI-DOCS:${esc} START[\\s\\S]*?<!-- AI-DOCS:${esc} END -->`)
  if (re.test(text)) return text.replace(re, () => block)
  const sep = text.endsWith("\n\n") ? "" : text.endsWith("\n") ? "\n" : "\n\n"
  return `${text}${sep}${block}\n`
}

function main() {
  const check = process.argv.includes("--check")
  const cfgAbs = join(REPO_ROOT, CONFIG_REL)
  if (!existsSync(cfgAbs)) {
    console.error(`No ${CONFIG_REL} at repo root.`)
    return 2
  }
  const cfg = JSON.parse(readFileSync(cfgAbs, "utf8"))
  const partials = loadPartials(join(REPO_ROOT, cfg.partialsDir || "ai/partials"))
  const issues = []
  const changed = []

  for (const [rel, spec] of Object.entries(cfg.targets || {})) {
    const abs = join(REPO_ROOT, rel)
    const original = existsSync(abs) ? normalize(readFileSync(abs, "utf8")) : null
    let text =
      original === null ? (spec.preamble ? normalize(spec.preamble) : `# ${rel}\n`) : original
    for (const req of spec.partials || []) {
      const key = partials[req] ? req : partialKey(req)
      const val = partials[key]
      if (!val) {
        const have = Object.keys(partials).sort().join(", ") || "none"
        issues.push(`${rel}: unknown partial "${req}" (have: ${have})`)
        continue
      }
      text = upsertBlock(text, key, blockFor(key, val.content, val.srcRel))
    }
    if (!text.endsWith("\n")) text += "\n"
    if (original === null || text !== original) {
      if (check) {
        const why = original === null ? "file missing" : "stale/hand-edited"
        issues.push(`DRIFT ${rel}: generated block differs from disk (${why})`)
      } else {
        mkdirSync(dirname(abs), { recursive: true })
        writeFileSync(abs, text, "utf8")
        changed.push(`${original === null ? "created" : "updated"} ${rel}`)
      }
    }
  }

  if (issues.length) {
    console.error(issues.join("\n"))
    if (check) console.error("\nFix: node tools/gen-ai-docs.mjs")
    return 1
  }
  if (check) {
    console.log("OK — AI instruction files in sync with ai/partials.")
    return 0
  }
  changed.forEach(c => console.log("  " + c))
  console.log(`OK — ${changed.length} file(s) written.`)
  return 0
}

process.exit(main())
